/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as UebungenRouteImport } from './routes/uebungen'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as KoerperRouteImport } from './routes/koerper'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsTemplateIdRouteImport } from './routes/workouts_.$templateId'
import { Route as UebungenExerciseIdRouteImport } from './routes/uebungen_.$exerciseId'
import { Route as JourneyWaehlenRouteImport } from './routes/journey_.waehlen'
import { Route as EinstellungenVersionRouteImport } from './routes/einstellungen_.version'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const UebungenRoute = UebungenRouteImport.update({
  id: '/uebungen',
  path: '/uebungen',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const KoerperRoute = KoerperRouteImport.update({
  id: '/koerper',
  path: '/koerper',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsTemplateIdRoute = WorkoutsTemplateIdRouteImport.update({
  id: '/workouts_/$templateId',
  path: '/workouts/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const UebungenExerciseIdRoute = UebungenExerciseIdRouteImport.update({
  id: '/uebungen_/$exerciseId',
  path: '/uebungen/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyWaehlenRoute = JourneyWaehlenRouteImport.update({
  id: '/journey_/waehlen',
  path: '/journey/waehlen',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenVersionRoute = EinstellungenVersionRouteImport.update({
  id: '/einstellungen_/version',
  path: '/einstellungen/version',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/journey': typeof JourneyRoute
  '/koerper': typeof KoerperRoute
  '/skills': typeof SkillsRoute
  '/uebungen': typeof UebungenRoute
  '/workouts': typeof WorkoutsRoute
  '/einstellungen/version': typeof EinstellungenVersionRoute
  '/journey/waehlen': typeof JourneyWaehlenRoute
  '/uebungen/$exerciseId': typeof UebungenExerciseIdRoute
  '/workouts/$templateId': typeof WorkoutsTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/journey': typeof JourneyRoute
  '/koerper': typeof KoerperRoute
  '/skills': typeof SkillsRoute
  '/uebungen': typeof UebungenRoute
  '/workouts': typeof WorkoutsRoute
  '/einstellungen/version': typeof EinstellungenVersionRoute
  '/journey/waehlen': typeof JourneyWaehlenRoute
  '/uebungen/$exerciseId': typeof UebungenExerciseIdRoute
  '/workouts/$templateId': typeof WorkoutsTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/einstellungen': typeof EinstellungenRoute
  '/journey': typeof JourneyRoute
  '/koerper': typeof KoerperRoute
  '/skills': typeof SkillsRoute
  '/uebungen': typeof UebungenRoute
  '/workouts': typeof WorkoutsRoute
  '/einstellungen_/version': typeof EinstellungenVersionRoute
  '/journey_/waehlen': typeof JourneyWaehlenRoute
  '/uebungen_/$exerciseId': typeof UebungenExerciseIdRoute
  '/workouts_/$templateId': typeof WorkoutsTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/einstellungen'
    | '/journey'
    | '/koerper'
    | '/skills'
    | '/uebungen'
    | '/workouts'
    | '/einstellungen/version'
    | '/journey/waehlen'
    | '/uebungen/$exerciseId'
    | '/workouts/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/einstellungen'
    | '/journey'
    | '/koerper'
    | '/skills'
    | '/uebungen'
    | '/workouts'
    | '/einstellungen/version'
    | '/journey/waehlen'
    | '/uebungen/$exerciseId'
    | '/workouts/$templateId'
  id:
    | '__root__'
    | '/'
    | '/einstellungen'
    | '/journey'
    | '/koerper'
    | '/skills'
    | '/uebungen'
    | '/workouts'
    | '/einstellungen_/version'
    | '/journey_/waehlen'
    | '/uebungen_/$exerciseId'
    | '/workouts_/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EinstellungenRoute: typeof EinstellungenRoute
  JourneyRoute: typeof JourneyRoute
  KoerperRoute: typeof KoerperRoute
  SkillsRoute: typeof SkillsRoute
  UebungenRoute: typeof UebungenRoute
  WorkoutsRoute: typeof WorkoutsRoute
  EinstellungenVersionRoute: typeof EinstellungenVersionRoute
  JourneyWaehlenRoute: typeof JourneyWaehlenRoute
  UebungenExerciseIdRoute: typeof UebungenExerciseIdRoute
  WorkoutsTemplateIdRoute: typeof WorkoutsTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uebungen': {
      id: '/uebungen'
      path: '/uebungen'
      fullPath: '/uebungen'
      preLoaderRoute: typeof UebungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koerper': {
      id: '/koerper'
      path: '/koerper'
      fullPath: '/koerper'
      preLoaderRoute: typeof KoerperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts_/$templateId': {
      id: '/workouts_/$templateId'
      path: '/workouts/$templateId'
      fullPath: '/workouts/$templateId'
      preLoaderRoute: typeof WorkoutsTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uebungen_/$exerciseId': {
      id: '/uebungen_/$exerciseId'
      path: '/uebungen/$exerciseId'
      fullPath: '/uebungen/$exerciseId'
      preLoaderRoute: typeof UebungenExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey_/waehlen': {
      id: '/journey_/waehlen'
      path: '/journey/waehlen'
      fullPath: '/journey/waehlen'
      preLoaderRoute: typeof JourneyWaehlenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen_/version': {
      id: '/einstellungen_/version'
      path: '/einstellungen/version'
      fullPath: '/einstellungen/version'
      preLoaderRoute: typeof EinstellungenVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EinstellungenRoute: EinstellungenRoute,
  JourneyRoute: JourneyRoute,
  KoerperRoute: KoerperRoute,
  SkillsRoute: SkillsRoute,
  UebungenRoute: UebungenRoute,
  WorkoutsRoute: WorkoutsRoute,
  EinstellungenVersionRoute: EinstellungenVersionRoute,
  JourneyWaehlenRoute: JourneyWaehlenRoute,
  UebungenExerciseIdRoute: UebungenExerciseIdRoute,
  WorkoutsTemplateIdRoute: WorkoutsTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
